apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: tensorflow-trainer
  name: tensorflow-trainer
spec:
  template:
    metadata:
      name: tensorflow-trainer
    spec:
      volumes:
      - name: binaries
        hostPath:
          path: /usr/bin/
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      containers:
      - command: ["/bin/sh", "-c"]
        args: ["export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu_custom:$LD_LIBRARY_PATH; python /app/TensorFlow_K8/TrainClassifier.py"]
        image: drcrook/cifar10:gpu
        imagePullPolicy: Always
        name: tensorflow-cifar10-train
        env:
        - name: STORAGE_ACCOUNT_NAME
          value: dasciencefiles
        - name: STORAGE_ACCOUNT_KEY
          value: HSTByj5U+I/uI0RBtSdl7eJEbnEUmkJIeTSj1bvYCr6MN9Yj0x0lHurLkjwm0xuxuColdTHAoveCpAZbDGOh7g==
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/bin/
          name: binaries
        - mountPath: /usr/lib/x86_64-linux-gnu_custom
          name: libraries
      restartPolicy: Never
