apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: roboarm-3
  name: roboarm-3
spec:
  template:
    metadata:
      name: roboarm-3
    spec:
      volumes:
      - name: t101
        azureFile:
            secretName: azure-secret
            shareName: t101
            readOnly: false
      - name: tensorboarddatashare
        azureFile:
            secretName: azure-secret
            shareName: tensorboard
            readOnly: false
      - name: binaries
        hostPath:
          path: /usr/bin/
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      containers:
      - command: ["/bin/sh", "-c"]
        args: ["export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu_custom:$LD_LIBRARY_PATH; python /app/TensorFlow_K8/TrainModel.py"]
        image: drcrook/cifar10:gpu
        imagePullPolicy: Always
        name: tensorflow-cifar10-train
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 2
        volumeMounts:
        - mountPath: "/t101"
          name: t101
        - mountPath: "/tensorboard"
          name: tensorboarddatashare
        - mountPath: /usr/bin/
          name: binaries
        - mountPath: /usr/lib/x86_64-linux-gnu_custom
          name: libraries
      restartPolicy: Never
